image: golang:1.20-bullseye

variables:
  BUILD_DIR: "build"
  BIN_NAME: "check_lsync_delay"

stages:
  - test
  - build
  - build-arm64

test:
  stage: test
  tags:
    - docker
  script:
    - make test

build:
  stage: build
  tags:
    - docker
  script:
    - make build-linux-amd64
  artifacts:
    paths:
      - ${BUILD_DIR}/linux-amd64/${BIN_NAME}
  rules:
    - if: $CI_COMMIT_TAG

build-arm64:
  stage: build-arm64
  tags:
    - docker
  script:
    - make build-linux-arm64
  artifacts:
    paths:
      - ${BUILD_DIR}/linux-arm64/${BIN_NAME}
  when: manual
